config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"

  namespace :admin do
    resources :categories
    resources :news
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :news
  validates :name, presence: true
  validates :description, presence: true, length: {minimum: 6}

  # scope :search, -> (keyword){where "name like ? or description like ?",
  #   "%#{keyword}%", "%#{keyword}%"}
end

app/models/news.rb
class News < ApplicationRecord
  belongs_to :category

  validates :title, presence: true
  validates :content, presence: true, length: {minimum: 5}
  validates :author, presence: true

  # scope :search, -> keyword do
  #   where "title like ? or content like ?", "%#{keyword}%", "%#{keyword}%" if keyword.present?
  # end

  scope :in_category, -> category_id do
    where category_id: category_id if category_id.present?
  end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  before_action :load_category, only: [:edit, :update, :destroy, :show]
  def index
    # if params[:search]
    #   @results_quantity = Category.search(params[:search]).count
    #   @categories = Category.search(params[:search]).order(created_at: :desc)
    #     .page(params[:page]).per Settings.admin.category.per_page
    # else
    #   @categories = Category.order(created_at: :desc)
    #     .page(params[:page]).per Settings.admin.category.per_page
    # end
    @search = Category.ransack(params[:q])
    @results_quantity = @search.result.count
    @categories = @search.result.order(created_at: :desc)
      .page(params[:page]).per Settings.admin.category.per_page
  end

  def show
  end

  def new
    @category = Category.new
  end

  def edit
  end

  def create
    @category = Category.new category_params
    if @category.save
      flash[:success] = "Add category success"
      redirect_to admin_categories_url
    else
      render :new
    end
  end

  def update
    if @category.update_attributes category_params
      flash[:success] = "Update cate success"
    else
      flash[:danger] = "Update cate failed"
    end
    redirect_to admin_categories_url
  end

  def destroy
    if @category.news.any?
      flash[:danger] = "Cannot delete category has any news"
    else
      if @category.destroy
        flash[:success] = "Delete cate success"
      else
        flash[:danger] = "Delete cate failed"
      end
    end
    redirect_to admin_categories_url
  end

  private
  def category_params
    params.require(:category).permit :name, :description
  end

  def load_category
    @category = Category.find_by id: params[:id]
    if @category.nil?
      flash[:danger] = "Cannot find category"
      redirect_to admin_categories_url
    end
  end
end

app/controllers/admin/news_controller.rb
class Admin::NewsController < ApplicationController
  before_action :load_categories, only: [:new, :create, :index, :edit]
  before_action :load_news, only: [:edit, :update, :destroy, :show]

  def index
    # @results_quantity = News.search(params[:search]).in_category(params[:category_id]).count
    @search = News.ransack(params[:q])
    @results_quantity = @search.result.count
    @news = @search.result.order(created_at: :desc)
      .page(params[:page]).per Settings.admin.news.per_page
  end

  def show
  end

  def new
    @news = News.new
  end

  def edit
    params[:category_id] = @news.category_id
  end

  def create
    @news = News.new news_params
    if @news.save
      flash[:success] = "Create news success"
      redirect_to admin_news_index_url
    else
      render :new
    end
  end

  def update
    if @news.update_attributes news_params
      flash[:success] = "Update news success"
      redirect_to admin_news_index_url
    else
      render :edit
    end
  end

  def destroy
    if @news.destroy
      flash[:success] = "Delete news success"
    else
      flash[:danger] = "Fail to delete news"
    end
    redirect_to admin_news_index_url
  end

  private
  def news_params
    params.require(:news).permit :title, :content, :author, :category_id
  end

  def load_categories
    @categories = Category.all
  end

  def load_news
    @news = News.find_by id: params[:id]
    if @news.nil?
      flash[:danger] = "Cannot found news"
      redirect_to admin_news_index_url
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/admin/news_helper.rb
module Admin::NewsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title page_title = ""
    base_title = "Demo App"
    page_title.empty? ? base_title : page_title + " | " + base_title
  end

  def get_index object, index, per_page
    (object.to_i - 1) * per_page + index + 1
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/admin/categories/_form.html.erb
<%= form_for [:admin, @category] do |f| %>
  <%= render "shared/error_messages", object: f.object %>
  <%= f.label :name %>
  <%= f.text_field :name, class: "form-control" %>

  <%= f.label :description %>
  <%= f.text_area :description, rows: 5, class: "form-control" %>

  <%= button_tag raw("<span class='glyphicon glyphicon-hand-right'></span> #{@submit}"),
    class: "btn btn-primary" %>
<% end %>

app/views/admin/categories/edit.html.erb
<% provide :title, "Edit category" %>
<% @submit = "Edit cate" %>

<%= link_to raw("<span class='glyphicon glyphicon-arrow-left'></span> Go back"),
  admin_categories_path, class: "btn btn-info" %>

<h1>Edit Category</h1>
<%= render "form" %>

app/views/admin/categories/index.html.erb
<% provide :title, "Manage Categories" %>

<div class="col-md-3 row">
  <%= link_to raw("<span class='glyphicon glyphicon-plus'></span> Add category"),
    new_admin_category_path, class: "btn btn-primary" %>
</div>

<div class="col-md-9 row search-cate">
  <%#= form_tag admin_categories_path, method: :get do %>
    <!-- <div class="col-md-6 col-md-offset-2 row"> -->
      <%#= text_field_tag :search, params[:search], class: "form-control",
        placeholder: "Search by name or description..." %>
    <!-- </div> -->
    <%#= submit_tag "Search", class: "btn btn-primary" %>
  <%# end %>

  <%= search_form_for [:admin, @search] do |f| %>
    <div class="col-md-6 col-md-offset-2 row">
      <%= f.search_field :name_or_description_cont, class: "form-control",
        placeholder: "search with ransack..." %>
    </div>
    <%= f.submit "Search", class: "btn btn-primary" %>
  <% end %>
</div>

<br><br><br><br>
<div class="search-result">
  <% if params[:q].present? && params[:q][:name_or_description_cont].present? %>
    Found <%= pluralize @results_quantity, "result" %> with keyword
      '<strong><%= params[:q][:name_or_description_cont] %></strong>'
  <% end %>
</div>
<br><br>
<table class="table table-hover table-striped table-bordered">
  <thead>
    <tr>
      <th>No.</th>
      <th>Name</th>
      <th>Description</th>
      <th>Number of news</th>
      <th>Created at</th>
      <th>Edit</th>
      <th>Delete</th>
    </tr>
  </thead>
  <tbody>
    <% if @categories.present? %>
      <% @categories.each_with_index do |category, index| %>
        <tr>
          <td>
            <% params[:page] ||= "1" %>
            <%= get_index params[:page], index, Settings.admin.category.per_page %>
          </td>
          <td>
            <%= link_to category.name, admin_category_path(category) %>
          </td>
          <td><%= category.description %></td>
          <td><%= category.news.size %></td>
          <td><%= l category.created_at, format: :long %></td>
          <td>
            <%= link_to raw("<span class='glyphicon glyphicon-edit'></span>"),
              edit_admin_category_path(category), class: "btn btn-warning" %>
          </td>
          <td>
            <%= link_to raw("<span class='glyphicon glyphicon-trash'></span>"), [:admin, category], method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-danger" %>
          </td>
        </tr>
      <% end %>
    <% else %>
      <tr><td colspan="7" class="table-no-data">No data</td></tr>
    <% end %>
  </tbody>
</table>

<%= paginate @categories, theme: "twitter-bootstrap-4" %>

app/views/admin/categories/new.html.erb
<% provide :title, "Add Category" %>
<% @submit = "Add new category" %>

<%= link_to raw("<span class='glyphicon glyphicon-arrow-left'></span> Go back"),
  admin_categories_path, class: "btn btn-info" %>

<h1>Add Category</h1>
<%= render "form" %>

app/views/admin/categories/show.html.erb
<% provide :title, "Show Category" %>

<%= link_to raw("<span class='glyphicon glyphicon-arrow-left'></span> Go back"),
  admin_categories_path, class: "btn btn-info" %>
<h1>Category Info</h1>

<table class="table table-bordered">
  <tr>
    <td>Name</td>
    <td><%= @category.name %></td>
  </tr>
  <tr>
    <td>Description</td>
    <td><%= @category.description %></td>
  </tr>
  <tr>
    <td>News</td>
    <td>
      <% if @category.news.any? %>
        <ul>
          <% @category.news.order(created_at: :desc).each do |news| %>
            <li><%= link_to news.title, admin_news_path(news) %></li>
          <% end %>
        </ul>
      <% else %>
      No news
      <% end %>
    </td>
  </tr>
</table>

app/views/admin/news/edit.html.erb
<% provide :title, "Edit news" %>

<%= link_to raw("<span class='glyphicon glyphicon-arrow-left'></span> Go back"),
  admin_news_index_path, class: "btn btn-info" %>

<h1>Edit news</h1>

<%= form_for [:admin, @news] do |f| %>
  <%= render "shared/error_messages", object: f.object %>

  <%= f.label :category_id, "Category" %>
  <div class="select-tag">
    <%= f.select :category_id, options_for_select(@categories.collect{|category|
      [category.name, category.id]}, params[:category_id]) %>
  </div>
  <br>
  <%= f.label :title %>
  <%= f.text_field :title, class: "form-control" %>

  <%= f.label :content %>
  <%= f.text_area :content, rows: 5, class: "form-control" %>

  <%= f.label :author %>
  <%= f.text_field :author, class: "form-control" %>

  <%= button_tag raw("<span class='glyphicon glyphicon-hand-right'></span> edit news"),
    class: "btn btn-primary" %>
<% end %>

app/views/admin/news/index.html.erb
<% provide :title, "Manage News" %>

<div class="col-md-3 row">
  <%= link_to raw("<span class='glyphicon glyphicon-plus'></span> Add News"),
    new_admin_news_path, class: "btn btn-primary" %>
</div>

<!-- ransack -->
<div class="col-md-9 col-md-offset-3 row">
  <%= search_form_for [:admin, @search] do |f| %>
    <div class="col-md-6">
      <%= f.search_field :title_or_content_cont, class: "form-control", placeholder: "Search by ransack..." %>
    </div>
    <div class="col-md-3 select-tag">
      <%= f.select :category_id_eq, options_for_select(@categories
        .collect{|category| [category.name, category.id]}, params[:q]), include_blank: "All" %>
    </div>
    <div class="col-md-3">
      <%= f.submit "Search", class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

<br><br><br><br>
<div class="search-result">
  <% if params[:q].present? && params[:q][:title_or_content_cont].present? %>
    Found '<strong><%= pluralize @search.result.size, "result" %></strong>'
  <% end %>
</div>
<br><br>
<table class="table table-hover table-bordered table-striped">
  <thead>
    <tr>
      <th>No.</th>
      <th>Category</th>
      <th>Title</th>
      <th>Content</th>
      <th>Author</th>
      <th>Created at</th>
      <th>Edit</th>
      <th>Delete</th>
    </tr>
  </thead>
  <tbody>
    <% if @news.present? %>
      <% @news.each_with_index do |news, index| %>
        <tr>
          <td>
            <% params[:page] ||= "1" %>
            <%= get_index params[:page], index, Settings.admin.news.per_page %>
          </td>
          <td><%= news.category.name %></td>
          <td><%= link_to news.title, admin_news_path(news) %></td>
          <td><%= news.content %></td>
          <td><%= news.author %></td>
          <td><%= l news.created_at, format: :long %></td>
          <td>
            <%= link_to raw("<span class='glyphicon glyphicon-edit'></span>"),
              edit_admin_news_path(news), class: "btn btn-warning" %>
          </td>
          <td>
            <%= link_to raw("<span class='glyphicon glyphicon-trash'></span>"), [:admin, news], method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-danger" %>
          </td>
        </tr>
      <% end %>
    <% else %>
      <tr><td colspan="8" class="table-no-data">No data</td></tr>
    <% end %>
  </tbody>
</table>

<%= paginate @news, theme: "twitter-bootstrap-4" %>

app/views/admin/news/new.html.erb
<% provide :title, "Add news" %>

<%= link_to raw("<span class='glyphicon glyphicon-arrow-left'></span> Go back"),
  admin_news_index_path, class: "btn btn-info" %>

<h1>Add news</h1>

<%= form_for [:admin, @news] do |f| %>
  <%= render "shared/error_messages", object: f.object %>

  <%= f.label :category_id, "Category" %>
  <div class="select-tag">
    <%= f.select :category_id, options_for_select(@categories.collect{|category|
      [category.name, category.id]}, params[:category_id]) %>
  </div>
  <br>
  <%= f.label :title %>
  <%= f.text_field :title, class: "form-control" %>

  <%= f.label :content %>
  <%= f.text_area :content, rows: 5, class: "form-control" %>

  <%= f.label :author %>
  <%= f.text_field :author, class: "form-control" %>

  <%= button_tag raw("<span class='glyphicon glyphicon-hand-right'></span> add news"),
    class: "btn btn-primary" %>
<% end %>

app/views/admin/news/show.html.erb
<% provide :title, "View news" %>

<%= link_to raw("<span class='glyphicon glyphicon-arrow-left'></span> Go back"),
  admin_news_index_path, class: "btn btn-info" %>

<h1>News Info</h1>

<table class="table table-bordered">
  <tr>
    <td>Title</td>
    <td><%= @news.title %></td>
  </tr>
  <tr>
    <td>Category</td>
    <td><%= link_to @news.category.name, admin_category_path(@news.category) %></td>
  </tr>
  <tr>
    <td>Content</td>
    <td><%= @news.content %></td>
  </tr>
  <tr>
    <td>Author</td>
    <td><%= @news.author %></td>
  </tr>
</table>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Homepage</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="/admin/categories">Categories</a></li>
        <li><a href="/admin/news">News</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title yield :title %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <div class="flash-message">
        <% flash.each do |message_type, message| %>
          <%= content_tag :div, message, class: "alert alert-#{message_type}" %>
        <% end %>
      </div>
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error-explanation">
    <div class="alert alert-danger">
      This form contains <%= pluralize object.errors.count, "error" %>
    </div>
    <ul>
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/home.html.erb
<h1>Home page</h1>